services:
  - type: web
    name: student-management-system
    env: node
    buildCommand: npm ci --legacy-peer-deps && chmod +x ./node_modules/.bin/vite && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    installCommand: npm install --legacy-peer-deps