services:
  - type: web
    name: student-management-system
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 16.20.2
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production